disable linting for now

diff --git a/.github/workflows/qc.yml b/.github/workflows/qc.yml
--- a/.github/workflows/qc.yml
+++ b/.github/workflows/qc.yml
@@ -58,19 +58,21 @@ jobs:
         run: |
           git fetch origin master
 
-      - name: Linting
-        shell: bash -el {0}
-        run: |
-          declare -i ERRORS=0
-          # get all modified and added files, not those that are deleted
-          for f in $(git diff origin/master --name-only --diff-filter=d | grep Snakefile)
-          do
-            echo "Linting $f"
-            (cd $(dirname $f) && snakemake --lint)
-            ERRORS+=$?
-          done
-          if (( $ERRORS > 0 ))
-          then
-            echo "There are some lints above. Please fix them."
-            exit 1
-          fi
+      # TODO reenable linting, but thereby allow that meta-wrappers refer to master/.../...
+      # This currently fails for meta-wrappers that are new, thus not yet in master
+      # - name: Linting
+      #   shell: bash -el {0}
+      #   run: |
+      #     declare -i ERRORS=0
+      #     # get all modified and added files, not those that are deleted
+      #     for f in $(git diff origin/master --name-only --diff-filter=d | grep Snakefile)
+      #     do
+      #       echo "Linting $f"
+      #       (cd $(dirname $f) && snakemake --lint)
+      #       ERRORS+=$?
+      #     done
+      #     if (( $ERRORS > 0 ))
+      #     then
+      #       echo "There are some lints above. Please fix them."
+      #       exit 1
+      #     fi
